name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CONTAINER: baybridge

jobs:
  docker-nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      run: |
        nix build .#docker
        docker load < result
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag & push docker image
      run: |
        docker tag $CONTAINER:latest ghcr.io/nicolaschan/$CONTAINER:latest
        docker push ghcr.io/nicolaschan/$CONTAINER:latest
        docker tag $CONTAINER:latest ghcr.io/nicolaschan/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}
        docker push ghcr.io/nicolaschan/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}

  docker-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      run: |
        nix build .#docker
        docker load < result
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag & push docker image
      run: |
        docker tag $CONTAINER:latest ghcr.io/nicolaschan/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}-arm64
        docker push ghcr.io/nicolaschan/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}-arm64

